[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = "0.3.0"
ruwren = "0.4.10"
vulkano = "0.34.1"
winit = "0.27.5"

[profile.dev]
opt-level = 1

[profile.release-lto]
inherits = "release"
lto = true
